In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/ravindrasinghrana/job-description-dataset/job_descriptions.csv

In [5]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("/kaggle/input/datasets/ravindrasinghrana/job-description-dataset/job_descriptions.csv")
df.dropna(inplace=True)

In [4]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [5]:
df.describe()

             Job Id      latitude     longitude  Company Size
count  1.615940e+06  1.615940e+06  1.615940e+06  1.615940e+06
mean   1.548935e+15  1.937743e+01  1.639926e+01  7.370467e+04
std    8.946722e+14  2.355690e+01  7.066762e+01  3.529886e+04
min    1.817948e+11 -4.090060e+01 -1.751982e+02  1.264600e+04
25%    7.740508e+14  5.152100e+00 -1.531010e+01  4.311400e+04
50%    1.547858e+15  1.807080e+01  1.914510e+01  7.363300e+04
75%    2.323729e+15  3.907420e+01  4.757690e+01  1.043000e+05
max    3.099618e+15  7.170690e+01  1.780650e+02  1.348340e+05

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615940 entries, 0 to 1615939
Data columns (total 23 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Job Id            1615940 non-null  int64
 1   Experience        1615940 non-null  object
 2   Qualifications    1615940 non-null  object
 3   Salary Range      1615940 non-null  object
 4   location          1615940 non-null  object
 5   Country           1615940 non-null  object
 6   latitude          1615940 non-null  float64
 7   longitude         1615940 non-null  float64
 8   Work Type         1615940 non-null  object
 9   Company Size      1615940 non-null  int64
 10  Job Posting Date  1615940 non-null  object
 11  Preference        1615940 non-null  object
 12  Contact Person    1615940 non-null  object
 13  Contact           1615940 non-null  object
 14  Job Title         1615940 non-null  object
 15  Role              1615940 non-null  object
 16  Job Portal        1615940 non-null  object
 17  Job Description   1615940 non-null  object
 18  Benefits          1615940 non-null  object
 19  skills            1615940 non-null  object
 20  Responsibilities  1615940 non-null  object
 21  Company           1615940 non-null  object
 22  Company Profile   1610462 non-null  object
dtypes: float64(2), int64(2), object(19)
memory usage: 283.6+ MB

In [7]:
df.shape

(1615940, 23)

In [8]:
df.Qualifications

0          M.Tech
1             BCA
2             PhD
3             PhD
4             MBA
            ...
1615935    B.Tech
1615936    M.Tech
1615937       BCA
1615938       BCA
1615939       BBA
Name: Qualifications, Length: 1615940, dtype: object

In [9]:
import pandas as pd
df = pd.read_csv("/kaggle/input/datasets/ravindrasinghrana/job-description-dataset/job_descriptions.csv")

In [10]:
df.rename(columns={'Job Id':'Job_Id','Salary Range':'Salary_Range','Work Type':'Work_Type','Company Size':'Company_Size','Job Posting Date':'Job_Posting_Date','Contact Person':'Contact_Person','Job Title':'Job_Title','Job Portal':'Job_Portal','Job Description':'Job_Description','Company Profile':'Company_Profile'},inplace=True)

In [11]:
df.Company_Profile

0          {"Sector":"Diversified","Industry":"Diversifie...
1          {"Sector":"Financial Services","Industry":"Com...
2          {"Sector":"Insurance","Industry":"Insurance: P...
3          {"Sector":"Energy","Industry":"Mining, Crude-O...
4          {"Sector":"Energy","Industry":"Energy - Oil & ...
                                 ...
1615935    {"Sector":"Food and Beverage/Confectionery","I...
1615936    {"Sector":"Energy","Industry":"Energy","City":...
1615937    {"Sector":"Technology","Industry":"Semiconduct...
1615938    {"Sector":"Automotive","Industry":"Automotive"...
1615939    {"Sector":"Equipment Rental","Industry":"Equip...
Name: Company_Profile, Length: 1615940, dtype: object

In [12]:
df.head(3)

,Job_Id,Experience,Qualifications,Salary_Range,location,Country,latitude,longitude,Work_Type,Company_Size,...,Contact,Job_Title,Role,Job_Portal,Job_Description,Benefits,skills,Responsibilities,Company,Company_Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."
2,481640072963533,0 to 12 Years,PhD,$61K-$104K,Macao,"Macao SAR, China",22.1987,113.5439,Temporary,84525,...,9687619505,Operations Manager,Quality Control Manager,Jobs2Careers,Quality Control Managers establish and enforce...,"{'Legal Assistance, Bonuses and Incentive Prog...",Quality control processes and methodologies St...,Establish and enforce quality control standard...,United Services Automobile Assn.,"{""Sector"":""Insurance"",""Industry"":""Insurance: P..."

In [13]:
df.isnull().sum()

Job_Id                 0
Experience             0
Qualifications         0
Salary_Range           0
location               0
Country                0
latitude               0
longitude              0
Work_Type              0
Company_Size           0
Job_Posting_Date       0
Preference             0
Contact_Person         0
Contact                0
Job_Title              0
Role                   0
Job_Portal             0
Job_Description        0
Benefits               0
skills                 0
Responsibilities       0
Company                0
Company_Profile     5478
dtype: int64

In [14]:
df.shape

(1615940, 23)

In [12]:
df.dropna(inplace=True)

In [10]:
df.isnull().sum()

Job Id              0
Experience          0
Qualifications      0
Salary Range        0
location            0
Country             0
latitude            0
longitude           0
Work Type           0
Company Size        0
Job Posting Date    0
Preference          0
Contact Person      0
Contact             0
Job Title           0
Role                0
Job Portal          0
Job Description     0
Benefits            0
skills              0
Responsibilities    0
Company             0
Company Profile     0
dtype: int64

In [11]:
df.drop_duplicates(inplace=True)